In [1]:
import pandas as pd
import numpy as np

In [2]:
dfo = pd.read_csv('flights.csv', low_memory=False)

In [3]:
dfo.memory_usage()

Index                       128
YEAR                   46552632
MONTH                  46552632
DAY                    46552632
DAY_OF_WEEK            46552632
AIRLINE                46552632
FLIGHT_NUMBER          46552632
TAIL_NUMBER            46552632
ORIGIN_AIRPORT         46552632
DESTINATION_AIRPORT    46552632
SCHEDULED_DEPARTURE    46552632
DEPARTURE_TIME         46552632
DEPARTURE_DELAY        46552632
TAXI_OUT               46552632
WHEELS_OFF             46552632
SCHEDULED_TIME         46552632
ELAPSED_TIME           46552632
AIR_TIME               46552632
DISTANCE               46552632
WHEELS_ON              46552632
TAXI_IN                46552632
SCHEDULED_ARRIVAL      46552632
ARRIVAL_TIME           46552632
ARRIVAL_DELAY          46552632
DIVERTED               46552632
CANCELLED              46552632
CANCELLATION_REASON    46552632
AIR_SYSTEM_DELAY       46552632
SECURITY_DELAY         46552632
AIRLINE_DELAY          46552632
LATE_AIRCRAFT_DELAY    46552632
WEATHER_DELAY          46552632
dtype: int64

In [4]:
dfo.head(10)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,1,1,4,DL,806,N3730B,SFO,MSP,25,...,610.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,1,1,4,NK,612,N635NK,LAS,MSP,25,...,509.0,-17.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,1,1,4,US,2013,N584UW,LAX,CLT,30,...,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,...,532.0,-13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,1,1,4,DL,1173,N826DN,LAS,ATL,30,...,656.0,-15.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = dfo.set_index(['DESTINATION_AIRPORT', 'AIRLINE'])
df = df.sort_index()
df.head()

                             YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  \
DESTINATION_AIRPORT AIRLINE
10135               DL       2015     10    1            4           2582
                    DL       2015     10    2            5           2582
                    DL       2015     10    3            6           2582
                    DL       2015     10    4            7           2582
                    DL       2015     10    5            1           2582

                            TAIL_NUMBER ORIGIN_AIRPORT  SCHEDULED_DEPARTURE  \
DESTINATION_AIRPORT AIRLINE
10135               DL           N993AT          10397                 2106
                    DL           N954AT          10397                 2106
                    DL           N955AT          10397                 2106
                    DL           N980AT          10397                 2106
                    DL           N993AT          10397                 2106

                             DEPARTURE_TIME  DEPARTURE_DELAY  ...  \
DESTINATION_AIRPORT AIRLINE                                   ...
10135               DL               2103.0             -3.0  ...
                    DL               2104.0             -2.0  ...
                    DL               2104.0             -2.0  ...
                    DL               2059.0             -7.0  ...
                    DL               2107.0              1.0  ...

                             ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
DESTINATION_AIRPORT AIRLINE
10135               DL             2257.0          -14.0         0          0
                    DL             2257.0          -14.0         0          0
                    DL             2253.0          -16.0         0          0
                    DL             2258.0          -13.0         0          0
                    DL             2312.0            1.0         0          0

                             CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
DESTINATION_AIRPORT AIRLINE
10135               DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN

                             SECURITY_DELAY  AIRLINE_DELAY  \
DESTINATION_AIRPORT AIRLINE
10135               DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN

                             LATE_AIRCRAFT_DELAY  WEATHER_DELAY
DESTINATION_AIRPORT AIRLINE
10135               DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN

[5 rows x 29 columns]

In [6]:
df_old = dfo[(dfo.AIRLINE == 'AA')&  (dfo.DESTINATION_AIRPORT == 'LAX')]
df_old.head(10)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
443,2015,1,1,4,AA,1361,N3KYAA,BNA,LAX,610,...,847.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
808,2015,1,1,4,AA,2401,N858AA,DFW,LAX,655,...,NaN,NaN,0,1,B,NaN,NaN,NaN,NaN,NaN
867,2015,1,1,4,AA,9,N792AA,JFK,LAX,700,...,1026.0,6.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
871,2015,1,1,4,AA,201,N3LJAA,BOS,LAX,700,...,1045.0,10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
880,2015,1,1,4,AA,1529,N5DHAA,MCO,LAX,700,...,926.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1006,2015,1,1,4,AA,1232,N7BKAA,MIA,LAX,705,...,940.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1097,2015,1,1,4,AA,1403,N3GDAA,AUS,LAX,715,...,911.0,31.0,0,0,NaN,0.0,0.0,31.0,0.0,0.0
1206,2015,1,1,4,AA,1209,N3LMAA,TPA,LAX,725,...,948.0,-7.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1255,2015,1,1,4,AA,76,N3HPAA,SFO,LAX,730,...,900.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1334,2015,1,1,4,AA,183,N3CBAA,LAS,LAX,735,...,856.0,6.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_new = df.xs(('LAX', 'AA'))
df_new.head()

                             YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA       2015      1    1            4           1361
                    AA       2015      1    1            4           2401
                    AA       2015      1    1            4              9
                    AA       2015      1    1            4            201
                    AA       2015      1    1            4           1529

                            TAIL_NUMBER ORIGIN_AIRPORT  SCHEDULED_DEPARTURE  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA           N3KYAA            BNA                  610
                    AA           N858AA            DFW                  655
                    AA           N792AA            JFK                  700
                    AA           N3LJAA            BOS                  700
                    AA           N5DHAA            MCO                  700

                             DEPARTURE_TIME  DEPARTURE_DELAY  ...  \
DESTINATION_AIRPORT AIRLINE                                   ...
LAX                 AA                607.0             -3.0  ...
                    AA                  NaN              NaN  ...
                    AA                649.0            -11.0  ...
                    AA                653.0             -7.0  ...
                    AA                658.0             -2.0  ...

                             ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA              847.0           -8.0         0          0
                    AA                NaN            NaN         0          1
                    AA             1026.0            6.0         0          0
                    AA             1045.0           10.0         0          0
                    AA              926.0           -9.0         0          0

                             CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA                       NaN               NaN
                    AA                         B               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN

                             SECURITY_DELAY  AIRLINE_DELAY  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN

                             LATE_AIRCRAFT_DELAY  WEATHER_DELAY
DESTINATION_AIRPORT AIRLINE
LAX                 AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN

[5 rows x 29 columns]

In [8]:
df.loc[("LAX","AA")]

                             YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA       2015      1    1            4           1361
                    AA       2015      1    1            4           2401
                    AA       2015      1    1            4              9
                    AA       2015      1    1            4            201
                    AA       2015      1    1            4           1529
...                           ...    ...  ...          ...            ...
                    AA       2015     12   31            4            640
                    AA       2015     12   31            4           1147
                    AA       2015     12   31            4            298
                    AA       2015     12   31            4             14
                    AA       2015     12   31            4            246

                            TAIL_NUMBER ORIGIN_AIRPORT  SCHEDULED_DEPARTURE  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA           N3KYAA            BNA                  610
                    AA           N858AA            DFW                  655
                    AA           N792AA            JFK                  700
                    AA           N3LJAA            BOS                  700
                    AA           N5DHAA            MCO                  700
...                                 ...            ...                  ...
                    AA           N176UW            PHX                 2105
                    AA           N3JKAA            MIA                 2144
                    AA           N850AA            HNL                 2225
                    AA           N858AA            OGG                 2246
                    AA           N863AA            KOA                 2326

                             DEPARTURE_TIME  DEPARTURE_DELAY  ...  \
DESTINATION_AIRPORT AIRLINE                                   ...
LAX                 AA                607.0             -3.0  ...
                    AA                  NaN              NaN  ...
                    AA                649.0            -11.0  ...
                    AA                653.0             -7.0  ...
                    AA                658.0             -2.0  ...
...                                     ...              ...  ...
                    AA               2103.0             -2.0  ...
                    AA               2142.0             -2.0  ...
                    AA               2219.0             -6.0  ...
                    AA                  2.0             76.0  ...
                    AA               2335.0              9.0  ...

                             ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA              847.0           -8.0         0          0
                    AA                NaN            NaN         0          1
                    AA             1026.0            6.0         0          0
                    AA             1045.0           10.0         0          0
                    AA              926.0           -9.0         0          0
...                                   ...            ...       ...        ...
                    AA             2126.0          -11.0         0          0
                    AA               41.0           -5.0         0          0
                    AA              521.0          -29.0         0          0
                    AA              653.0           55.0         0          0
                    AA              635.0           -2.0         0          0

                             CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA                       NaN               NaN
                    AA                         B               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN
...                                          ...               ...
                    AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               0.0
                    AA                       NaN               NaN

                             SECURITY_DELAY  AIRLINE_DELAY  \
DESTINATION_AIRPORT AIRLINE
LAX                 AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
...                                     ...            ...
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  0.0           24.0
                    AA                  NaN            NaN

                             LATE_AIRCRAFT_DELAY  WEATHER_DELAY
DESTINATION_AIRPORT AIRLINE
LAX                 AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
...                                          ...            ...
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                      31.0            0.0
                    AA                       NaN            NaN

[32745 rows x 29 columns]

In [12]:
df.FLIGHT_NUMBER['LAX','AA']

DESTINATION_AIRPORT  AIRLINE
LAX                  AA         1361
                     AA         2401
                     AA            9
                     AA          201
                     AA         1529
                                ...
                     AA          640
                     AA         1147
                     AA          298
                     AA           14
                     AA          246
Name: FLIGHT_NUMBER, Length: 32745, dtype: int64

In [14]:
# Slicing in a multindex object
df_int = df.loc["AAA":]
df_int

                             YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL       2015      1    4            7           2036
                    DL       2015      1    5            1           1411
                    DL       2015      1    6            2           1411
                    DL       2015      1    7            3           1411
                    DL       2015      1    8            4           1411
...                           ...    ...  ...          ...            ...
YUM                 OO       2015     12   31            4           2991
                    OO       2015     12   31            4           2961
                    OO       2015     12   31            4           2956
                    OO       2015     12   31            4           2963
                    OO       2015     12   31            4           2973

                            TAIL_NUMBER ORIGIN_AIRPORT  SCHEDULED_DEPARTURE  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL           N979AT            ATL                 2101
                    DL           N989AT            ATL                 2034
                    DL           N979AT            ATL                 2034
                    DL           N958AT            ATL                 2034
                    DL           N994AT            ATL                 2034
...                                 ...            ...                  ...
YUM                 OO           N464SW            PHX                  945
                    OO           N869AS            PHX                 1100
                    OO           N821AS            PHX                 1440
                    OO           N821AS            PHX                 1740
                    OO           N869AS            PHX                 2235

                             DEPARTURE_TIME  DEPARTURE_DELAY  ...  \
DESTINATION_AIRPORT AIRLINE                                   ...
ABE                 DL               2101.0              0.0  ...
                    DL               2032.0             -2.0  ...
                    DL               2032.0             -2.0  ...
                    DL               2031.0             -3.0  ...
                    DL               2030.0             -4.0  ...
...                                     ...              ...  ...
YUM                 OO                942.0             -3.0  ...
                    OO               1100.0              0.0  ...
                    OO               1436.0             -4.0  ...
                    OO               1736.0             -4.0  ...
                    OO               2227.0             -8.0  ...

                             ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL             2252.0            1.0         0          0
                    DL             2227.0            2.0         0          0
                    DL             2221.0           -4.0         0          0
                    DL             2226.0            1.0         0          0
                    DL             2223.0           -2.0         0          0
...                                   ...            ...       ...        ...
YUM                 OO             1041.0           -7.0         0          0
                    OO             1203.0            0.0         0          0
                    OO             1536.0           -3.0         0          0
                    OO             1828.0           -7.0         0          0
                    OO             2308.0          -20.0         0          0

                             CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
...                                          ...               ...
YUM                 OO                       NaN               NaN
                    OO                       NaN               NaN
                    OO                       NaN               NaN
                    OO                       NaN               NaN
                    OO                       NaN               NaN

                             SECURITY_DELAY  AIRLINE_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
...                                     ...            ...
YUM                 OO                  NaN            NaN
                    OO                  NaN            NaN
                    OO                  NaN            NaN
                    OO                  NaN            NaN
                    OO                  NaN            NaN

                             LATE_AIRCRAFT_DELAY  WEATHER_DELAY
DESTINATION_AIRPORT AIRLINE
ABE                 DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
...                                          ...            ...
YUM                 OO                       NaN            NaN
                    OO                       NaN            NaN
                    OO                       NaN            NaN
                    OO                       NaN            NaN
                    OO                       NaN            NaN

[5332914 rows x 29 columns]

In [15]:
df_int.loc[("ABE","AA"):("ABZ","MM")]

                             YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL       2015      1    4            7           2036
                    DL       2015      1    5            1           1411
                    DL       2015      1    6            2           1411
                    DL       2015      1    7            3           1411
                    DL       2015      1    8            4           1411
...                           ...    ...  ...          ...            ...
ABY                 EV       2015     12   29            2           5334
                    EV       2015     12   29            2           5351
                    EV       2015     12   30            3           5334
                    EV       2015     12   30            3           5351
                    EV       2015     12   31            4           5334

                            TAIL_NUMBER ORIGIN_AIRPORT  SCHEDULED_DEPARTURE  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL           N979AT            ATL                 2101
                    DL           N989AT            ATL                 2034
                    DL           N979AT            ATL                 2034
                    DL           N958AT            ATL                 2034
                    DL           N994AT            ATL                 2034
...                                 ...            ...                  ...
ABY                 EV           N856AS            ATL                 1339
                    EV           N873AS            ATL                 2054
                    EV           N859AS            ATL                 1339
                    EV           N878AS            ATL                 2054
                    EV           N859AS            ATL                 1340

                             DEPARTURE_TIME  DEPARTURE_DELAY  ...  \
DESTINATION_AIRPORT AIRLINE                                   ...
ABE                 DL               2101.0              0.0  ...
                    DL               2032.0             -2.0  ...
                    DL               2032.0             -2.0  ...
                    DL               2031.0             -3.0  ...
                    DL               2030.0             -4.0  ...
...                                     ...              ...  ...
ABY                 EV               1336.0             -3.0  ...
                    EV               2047.0             -7.0  ...
                    EV               1427.0             48.0  ...
                    EV               2220.0             86.0  ...
                    EV               1357.0             17.0  ...

                             ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL             2252.0            1.0         0          0
                    DL             2227.0            2.0         0          0
                    DL             2221.0           -4.0         0          0
                    DL             2226.0            1.0         0          0
                    DL             2223.0           -2.0         0          0
...                                   ...            ...       ...        ...
ABY                 EV             1424.0           -7.0         0          0
                    EV             2148.0            4.0         0          0
                    EV             1524.0           53.0         0          0
                    EV             2309.0           85.0         0          0
                    EV             1456.0           24.0         0          0

                             CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
...                                          ...               ...
ABY                 EV                       NaN               NaN
                    EV                       NaN               NaN
                    EV                       NaN               5.0
                    EV                       NaN               0.0
                    EV                       NaN               7.0

                             SECURITY_DELAY  AIRLINE_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
...                                     ...            ...
ABY                 EV                  NaN            NaN
                    EV                  NaN            NaN
                    EV                  0.0           20.0
                    EV                  0.0           85.0
                    EV                  0.0           17.0

                             LATE_AIRCRAFT_DELAY  WEATHER_DELAY
DESTINATION_AIRPORT AIRLINE
ABE                 DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
...                                          ...            ...
ABY                 EV                       NaN            NaN
                    EV                       NaN            NaN
                    EV                      28.0            0.0
                    EV                       0.0            0.0
                    EV                       0.0            0.0

[25338 rows x 29 columns]

In [16]:
# Ever airport destination but only American Airlines.
df_int.loc[(slice(None),'AA'),:]

                             YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA       2015      1    1            4           1662
                    AA       2015      1    1            4           1024
                    AA       2015      1    1            4           1203
                    AA       2015      1    1            4           2388
                    AA       2015      1    2            5           1662
...                           ...    ...  ...          ...            ...
XNA                 AA       2015      6    6            6           1645
                    AA       2015      6    6            6            307
                    AA       2015      6    6            6           1694
                    AA       2015     11   23            1           2531
                    AA       2015     11   23            1           2291

                            TAIL_NUMBER ORIGIN_AIRPORT  SCHEDULED_DEPARTURE  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA           N4WJAA            DFW                 1045
                    AA           N505AA            DFW                 1400
                    AA           N4XPAA            DFW                 1840
                    AA           N486AA            DFW                 2115
                    AA           N582AA            DFW                 1045
...                                 ...            ...                  ...
XNA                 AA           N5CKAA            DFW                  805
                    AA           N574AA            DFW                  920
                    AA           N5CKAA            DFW                 1430
                    AA           N403AA            DFW                 1530
                    AA           N403AA            DFW                 2005

                             DEPARTURE_TIME  DEPARTURE_DELAY  ...  \
DESTINATION_AIRPORT AIRLINE                                   ...
ABQ                 AA                  NaN              NaN  ...
                    AA               1408.0              8.0  ...
                    AA               1853.0             13.0  ...
                    AA               2126.0             11.0  ...
                    AA               1044.0             -1.0  ...
...                                     ...              ...  ...
XNA                 AA                755.0            -10.0  ...
                    AA                920.0              0.0  ...
                    AA               1421.0             -9.0  ...
                    AA               1526.0             -4.0  ...
                    AA               2000.0             -5.0  ...

                             ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA                NaN            NaN         0          1
                    AA             1500.0           10.0         0          0
                    AA             1953.0           23.0         0          0
                    AA             2210.0           10.0         0          0
                    AA             1126.0           -9.0         0          0
...                                   ...            ...       ...        ...
XNA                 AA              902.0          -10.0         0          0
                    AA             1023.0          -11.0         0          0
                    AA             1528.0          -10.0         0          0
                    AA             1624.0          -15.0         0          0
                    AA             2102.0          -11.0         0          0

                             CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA                         B               NaN
                    AA                       NaN               NaN
                    AA                       NaN              10.0
                    AA                       NaN               NaN
                    AA                       NaN               NaN
...                                          ...               ...
XNA                 AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN

                             SECURITY_DELAY  AIRLINE_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  0.0            0.0
                    AA                  NaN            NaN
                    AA                  NaN            NaN
...                                     ...            ...
XNA                 AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN

                             LATE_AIRCRAFT_DELAY  WEATHER_DELAY
DESTINATION_AIRPORT AIRLINE
ABQ                 AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       6.0            7.0
                    AA                       NaN            NaN
                    AA                       NaN            NaN
...                                          ...            ...
XNA                 AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN

[648694 rows x 29 columns]

In [17]:
idx = pd.IndexSlice
df_int.loc[idx[:,"AA"],:]

                             YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA       2015      1    1            4           1662
                    AA       2015      1    1            4           1024
                    AA       2015      1    1            4           1203
                    AA       2015      1    1            4           2388
                    AA       2015      1    2            5           1662
...                           ...    ...  ...          ...            ...
XNA                 AA       2015      6    6            6           1645
                    AA       2015      6    6            6            307
                    AA       2015      6    6            6           1694
                    AA       2015     11   23            1           2531
                    AA       2015     11   23            1           2291

                            TAIL_NUMBER ORIGIN_AIRPORT  SCHEDULED_DEPARTURE  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA           N4WJAA            DFW                 1045
                    AA           N505AA            DFW                 1400
                    AA           N4XPAA            DFW                 1840
                    AA           N486AA            DFW                 2115
                    AA           N582AA            DFW                 1045
...                                 ...            ...                  ...
XNA                 AA           N5CKAA            DFW                  805
                    AA           N574AA            DFW                  920
                    AA           N5CKAA            DFW                 1430
                    AA           N403AA            DFW                 1530
                    AA           N403AA            DFW                 2005

                             DEPARTURE_TIME  DEPARTURE_DELAY  ...  \
DESTINATION_AIRPORT AIRLINE                                   ...
ABQ                 AA                  NaN              NaN  ...
                    AA               1408.0              8.0  ...
                    AA               1853.0             13.0  ...
                    AA               2126.0             11.0  ...
                    AA               1044.0             -1.0  ...
...                                     ...              ...  ...
XNA                 AA                755.0            -10.0  ...
                    AA                920.0              0.0  ...
                    AA               1421.0             -9.0  ...
                    AA               1526.0             -4.0  ...
                    AA               2000.0             -5.0  ...

                             ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA                NaN            NaN         0          1
                    AA             1500.0           10.0         0          0
                    AA             1953.0           23.0         0          0
                    AA             2210.0           10.0         0          0
                    AA             1126.0           -9.0         0          0
...                                   ...            ...       ...        ...
XNA                 AA              902.0          -10.0         0          0
                    AA             1023.0          -11.0         0          0
                    AA             1528.0          -10.0         0          0
                    AA             1624.0          -15.0         0          0
                    AA             2102.0          -11.0         0          0

                             CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA                         B               NaN
                    AA                       NaN               NaN
                    AA                       NaN              10.0
                    AA                       NaN               NaN
                    AA                       NaN               NaN
...                                          ...               ...
XNA                 AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN
                    AA                       NaN               NaN

                             SECURITY_DELAY  AIRLINE_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABQ                 AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  0.0            0.0
                    AA                  NaN            NaN
                    AA                  NaN            NaN
...                                     ...            ...
XNA                 AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN
                    AA                  NaN            NaN

                             LATE_AIRCRAFT_DELAY  WEATHER_DELAY
DESTINATION_AIRPORT AIRLINE
ABQ                 AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       6.0            7.0
                    AA                       NaN            NaN
                    AA                       NaN            NaN
...                                          ...            ...
XNA                 AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN
                    AA                       NaN            NaN

[648694 rows x 29 columns]

In [18]:

df_int.loc[idx['A':'B',"D":"F"],:]

                             YEAR  MONTH  DAY  DAY_OF_WEEK  FLIGHT_NUMBER  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL       2015      1    4            7           2036
                    DL       2015      1    5            1           1411
                    DL       2015      1    6            2           1411
                    DL       2015      1    7            3           1411
                    DL       2015      1    8            4           1411
...                           ...    ...  ...          ...            ...
AZO                 EV       2015     12   30            3           4137
                    EV       2015     12   30            3           4408
                    EV       2015     12   31            4           4935
                    EV       2015     12   31            4           4116
                    EV       2015     12   31            4           4137

                            TAIL_NUMBER ORIGIN_AIRPORT  SCHEDULED_DEPARTURE  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL           N979AT            ATL                 2101
                    DL           N989AT            ATL                 2034
                    DL           N979AT            ATL                 2034
                    DL           N958AT            ATL                 2034
                    DL           N994AT            ATL                 2034
...                                 ...            ...                  ...
AZO                 EV           N12195            ORD                 1552
                    EV           N23139            ORD                 2052
                    EV           N750EV            DTW                  830
                    EV           N16999            ORD                 1220
                    EV           N11165            ORD                 1552

                             DEPARTURE_TIME  DEPARTURE_DELAY  ...  \
DESTINATION_AIRPORT AIRLINE                                   ...
ABE                 DL               2101.0              0.0  ...
                    DL               2032.0             -2.0  ...
                    DL               2032.0             -2.0  ...
                    DL               2031.0             -3.0  ...
                    DL               2030.0             -4.0  ...
...                                     ...              ...  ...
AZO                 EV               1548.0             -4.0  ...
                    EV               2111.0             19.0  ...
                    EV                834.0              4.0  ...
                    EV               1217.0             -3.0  ...
                    EV               1547.0             -5.0  ...

                             ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL             2252.0            1.0         0          0
                    DL             2227.0            2.0         0          0
                    DL             2221.0           -4.0         0          0
                    DL             2226.0            1.0         0          0
                    DL             2223.0           -2.0         0          0
...                                   ...            ...       ...        ...
AZO                 EV             1732.0          -20.0         0          0
                    EV             2256.0            4.0         0          0
                    EV              920.0          -12.0         0          0
                    EV             1409.0          -11.0         0          0
                    EV             1729.0          -23.0         0          0

                             CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
                    DL                       NaN               NaN
...                                          ...               ...
AZO                 EV                       NaN               NaN
                    EV                       NaN               NaN
                    EV                       NaN               NaN
                    EV                       NaN               NaN
                    EV                       NaN               NaN

                             SECURITY_DELAY  AIRLINE_DELAY  \
DESTINATION_AIRPORT AIRLINE
ABE                 DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
                    DL                  NaN            NaN
...                                     ...            ...
AZO                 EV                  NaN            NaN
                    EV                  NaN            NaN
                    EV                  NaN            NaN
                    EV                  NaN            NaN
                    EV                  NaN            NaN

                             LATE_AIRCRAFT_DELAY  WEATHER_DELAY
DESTINATION_AIRPORT AIRLINE
ABE                 DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
                    DL                       NaN            NaN
...                                          ...            ...
AZO                 EV                       NaN            NaN
                    EV                       NaN            NaN
                    EV                       NaN            NaN
                    EV                       NaN            NaN
                    EV                       NaN            NaN

[303663 rows x 29 columns]